//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndderControl.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndderControl.Text.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARE RESULTS.
        /// </summary>
        public static string AssessCompareButton {
            get {
                return ResourceManager.GetString("AssessCompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS SELECTIVE DRY COW TREATMENT?.
        /// </summary>
        public static string AssessPageTitle {
            get {
                return ResourceManager.GetString("AssessPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START QUESTIONS.
        /// </summary>
        public static string AssessQuestionButton {
            get {
                return ResourceManager.GetString("AssessQuestionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY OF RESULTS.
        /// </summary>
        public static string AssessSummaryButton {
            get {
                return ResourceManager.GetString("AssessSummaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT is widely regarded best practice during dry off and essential in reducing the use of antibiotics in the dairy industry. MSD Animal Health has provided this tool to assist vets and farmers to assess whether SDCT is right for them and then monitor success after SDCT has been implemented..
        /// </summary>
        public static string AssessText1 {
            get {
                return ResourceManager.GetString("AssessText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a farm has been analysed and the process of monitoring has begun, SDCT can help reduce the economic loss from discarded milk, medicine and treatment costs. Farm analysis and monitoring resulting in better management, can reduce the threat of new infection and the associated fatality costs, increased culling costs and reduced yield for
        ///the lactation..
        /// </summary>
        public static string AssessText2 {
            get {
                return ResourceManager.GetString("AssessText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT is based on analysing and monitoring the herd by gathering data through regular and repeated cow SCCs and accurate infection records..
        /// </summary>
        public static string AssessText3 {
            get {
                return ResourceManager.GetString("AssessText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT can only be used if other best practice procedures are put into place, and this app will help to establish a pathway to using SDCT as common practice.
        ///All farms must conduct monthly cow SCC measurements (last cow SCC before dry off and the first SCC after calving) before implementing SDCT, or alternatively you may use another reliable test..
        /// </summary>
        public static string AssessText4 {
            get {
                return ResourceManager.GetString("AssessText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTIVE DRY COW TREATMENT (SDCT) IS....
        /// </summary>
        public static string AssessTitle1 {
            get {
                return ResourceManager.GetString("AssessTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW WILL SDCT HELP MY FARM?.
        /// </summary>
        public static string AssessTitle2 {
            get {
                return ResourceManager.GetString("AssessTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO IMPLEMENT SDCT ON MY FARM?.
        /// </summary>
        public static string AssessTitle3 {
            get {
                return ResourceManager.GetString("AssessTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM I ELIGIBLE FOR SDCT?.
        /// </summary>
        public static string AssessTitle4 {
            get {
                return ResourceManager.GetString("AssessTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARE RESULTS.
        /// </summary>
        public static string MonitorCompareButton {
            get {
                return ResourceManager.GetString("MonitorCompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS SELECTIVE DRY COW TREATMENT WORKING?.
        /// </summary>
        public static string MonitorPageTitle {
            get {
                return ResourceManager.GetString("MonitorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COW STATUS INPUT.
        /// </summary>
        public static string MonitorStatusButton {
            get {
                return ResourceManager.GetString("MonitorStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY OF RESULTS.
        /// </summary>
        public static string MonitorSummaryButton {
            get {
                return ResourceManager.GetString("MonitorSummaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once SDCT has been implemented, continuous monitoring is required in order to refine practices on farm in order to optimise success levels and ultimately productivity, profitability and animal welfare..
        /// </summary>
        public static string MonitorText1 {
            get {
                return ResourceManager.GetString("MonitorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app will help you to analyse the infection rates of the herd at dry-off and calving. By inputing the infection status of each cow in the herd you can monitor the overall results and analyse which areas are working well and where improvement may be required..
        /// </summary>
        public static string MonitorText2 {
            get {
                return ResourceManager.GetString("MonitorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcoming problems is part of everyday life when managing a dairy herd and SDCT is no different, by fostering good working relationships, MSD Animal Health Representatives, vets and farmers can work together to overcome any challenges which may arise..
        /// </summary>
        public static string MonitorText3 {
            get {
                return ResourceManager.GetString("MonitorText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT provides both short term and long term benefits; reducing antibiotic use in the food chain, improving productivity and reducing infection treatment costs are all strong reasons to implement and maintain SDCT..
        /// </summary>
        public static string MonitorText4 {
            get {
                return ResourceManager.GetString("MonitorText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT IS IMPORTANT TO CONTINUE MONITORING
        ///THE FARM ONCE SDCT IS IMPLEMENTED....
        /// </summary>
        public static string MonitorTitle1 {
            get {
                return ResourceManager.GetString("MonitorTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT YOU NEED TO MONITOR....
        /// </summary>
        public static string MonitorTitle2 {
            get {
                return ResourceManager.GetString("MonitorTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO DEAL WITH ANY PROBLEMS WHICH
        ///MAY ARISE....
        /// </summary>
        public static string MonitorTitle3 {
            get {
                return ResourceManager.GetString("MonitorTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE BENEFITS OF MAINTAINING SDCT....
        /// </summary>
        public static string MonitorTitle4 {
            get {
                return ResourceManager.GetString("MonitorTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ornare libero a dictum. Nullam dictum lacinia lectus, a condimentum erat venenatis in. Vivamus gravida eu sem eu cursus. Fusce fermentum, felis eu malesuada elementum, neque ipsum sodales turpis, feugiat pulvinar orci lectus vitae ipsum. Aenean congue tristique nulla, at consectetur risus lobortis non. In eu leo ante. Donec a faucibus elit, vel consectetur nisi. Praesent consectetur leo non sagittis hendrerit.
        ///
        ///Sed sit amet leo eu jus [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
    }
}
