//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndderControl.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppTextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndderControl.Text.AppTextResource", typeof(AppTextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREAS WHICH HAVE IMPROVED.
        /// </summary>
        public static string AreasWhichHaveImproved {
            get {
                return ResourceManager.GetString("AreasWhichHaveImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREAS WHICH HAVE IMPROVED BUT STILL NEED IMPROVEMENT.
        /// </summary>
        public static string AreasWhichHaveImprovedButStillNeedImprovement {
            get {
                return ResourceManager.GetString("AreasWhichHaveImprovedButStillNeedImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREAS WHICH NEED IMPROVEMENT.
        /// </summary>
        public static string AreasWhichNeedImprovement {
            get {
                return ResourceManager.GetString("AreasWhichNeedImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREAS WHICH REMAINED STABLE BUT STILL NEED IMPROVEMENT.
        /// </summary>
        public static string AreasWhichRemainedStableButStillNeedImprovement {
            get {
                return ResourceManager.GetString("AreasWhichRemainedStableButStillNeedImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARE RESULTS.
        /// </summary>
        public static string AssessCompareButton {
            get {
                return ResourceManager.GetString("AssessCompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START QUESTIONS.
        /// </summary>
        public static string AssessQuestionButton {
            get {
                return ResourceManager.GetString("AssessQuestionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY OF RESULTS.
        /// </summary>
        public static string AssessSummaryButton {
            get {
                return ResourceManager.GetString("AssessSummaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT is widely regarded best practice during dry-off and essential in responsible usage of antibiotics in the dairy industry. MSD Animal Health has provided this tool to assist vets and farmers to assess whether the farm is ready to implement SDCT and then monitor success after SDCT has been implemented..
        /// </summary>
        public static string AssessText1 {
            get {
                return ResourceManager.GetString("AssessText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a farm has been analysed and the process of monitoring has begun, SDCT can help reduce the economic loss from discarded milk, medicine and treatment costs. Farm analysis and monitoring resulting in better management, can reduce the threat of new infection and the associated fatality costs, increased culling costs and reduced yield for the lactation..
        /// </summary>
        public static string AssessText2 {
            get {
                return ResourceManager.GetString("AssessText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT is based on analysing and monitoring the herd by gathering data through regular and repeated cow SCCs and accurate infection records and diagnostics..
        /// </summary>
        public static string AssessText3 {
            get {
                return ResourceManager.GetString("AssessText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT can only be used if other best practice procedures are put into place, and this app will help to establish a pathway to using SDCT as common practice.
        ///All farms must conduct monthly cow SCC measurements (last cow SCC before dry-off and the first SCC after calving) before implementing SDCT, or alternatively you may use another reliable test..
        /// </summary>
        public static string AssessText4 {
            get {
                return ResourceManager.GetString("AssessText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTIVE DRY COW TREATMENT (SDCT) IS....
        /// </summary>
        public static string AssessTitle1 {
            get {
                return ResourceManager.GetString("AssessTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW WILL SDCT HELP MY FARM?.
        /// </summary>
        public static string AssessTitle2 {
            get {
                return ResourceManager.GetString("AssessTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO IMPLEMENT SDCT ON MY FARM?.
        /// </summary>
        public static string AssessTitle3 {
            get {
                return ResourceManager.GetString("AssessTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM I ELIGIBLE FOR SDCT?.
        /// </summary>
        public static string AssessTitle4 {
            get {
                return ResourceManager.GetString("AssessTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALVING.
        /// </summary>
        public static string CowStatusButtonCalving {
            get {
                return ResourceManager.GetString("CowStatusButtonCalving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRY-OFF.
        /// </summary>
        public static string CowStatusButtonDryOff {
            get {
                return ResourceManager.GetString("CowStatusButtonDryOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANK YOU FOR PROVIDING THE DATA FOR THE DRY-OFF PERIOD..
        /// </summary>
        public static string CowStatusFinishText1 {
            get {
                return ResourceManager.GetString("CowStatusFinishText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results and comparisons will be available once the calving data has been completed..
        /// </summary>
        public static string CowStatusFinishText2 {
            get {
                return ResourceManager.GetString("CowStatusFinishText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH.
        /// </summary>
        public static string CowStatusInputButtonFinish {
            get {
                return ResourceManager.GetString("CowStatusInputButtonFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string CowStatusInputButtonNext {
            get {
                return ResourceManager.GetString("CowStatusInputButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the relevant option.
        /// </summary>
        public static string CowStatusInputCaption {
            get {
                return ResourceManager.GetString("CowStatusInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COW I.D..
        /// </summary>
        public static string CowStatusInputLabel {
            get {
                return ResourceManager.GetString("CowStatusInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS AT CALVING.
        /// </summary>
        public static string CowStatusInputTextCalvingStatus {
            get {
                return ResourceManager.GetString("CowStatusInputTextCalvingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS AT DRY-OFF.
        /// </summary>
        public static string CowStatusInputTextDryoffStatus {
            get {
                return ResourceManager.GetString("CowStatusInputTextDryoffStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT DATA.
        /// </summary>
        public static string CowStatusInputTitle {
            get {
                return ResourceManager.GetString("CowStatusInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COW STATUS.
        /// </summary>
        public static string CowStatusPageTitle {
            get {
                return ResourceManager.GetString("CowStatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once SDCT has been implemented on farm it is important to monitor the herd to catch and fix any issues which may arise..
        /// </summary>
        public static string CowStatusText1 {
            get {
                return ResourceManager.GetString("CowStatusText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to input the cow’s status at &lt;b&gt;DRY-OFF&lt;/b&gt; and &lt;b&gt;CALVING&lt;/b&gt;..
        /// </summary>
        public static string CowStatusText2 {
            get {
                return ResourceManager.GetString("CowStatusText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data will be analysed and results will be available after calving information has been input..
        /// </summary>
        public static string CowStatusText3 {
            get {
                return ResourceManager.GetString("CowStatusText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition of &lt;b&gt;‘infected’&lt;/b&gt; is based on the internationally agreed SCC threshold of 200k cells/ml, or alternatively you may use your own threshold if desired..
        /// </summary>
        public static string CowStatusText4 {
            get {
                return ResourceManager.GetString("CowStatusText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SCC measurements must be taken within 30 days of input..
        /// </summary>
        public static string CowStatusText5 {
            get {
                return ResourceManager.GetString("CowStatusText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURE.
        /// </summary>
        public static string CsCure {
            get {
                return ResourceManager.GetString("CsCure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILURE TO CURE.
        /// </summary>
        public static string CsFailureToCure {
            get {
                return ResourceManager.GetString("CsFailureToCure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFECTED AFTER CALVING.
        /// </summary>
        public static string CsInfectedAfterCalving {
            get {
                return ResourceManager.GetString("CsInfectedAfterCalving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFECTED AT DRY-OFF.
        /// </summary>
        public static string CsInfectedAtDryoff {
            get {
                return ResourceManager.GetString("CsInfectedAtDryoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW INFECTION.
        /// </summary>
        public static string CsNewInfection {
            get {
                return ResourceManager.GetString("CsNewInfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT INFECTED AFTER CALVING.
        /// </summary>
        public static string CsNotInfectedAfterCalving {
            get {
                return ResourceManager.GetString("CsNotInfectedAfterCalving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT INFECTED AT DRY-OFF.
        /// </summary>
        public static string CsNotInfectedAtDryoff {
            get {
                return ResourceManager.GetString("CsNotInfectedAtDryoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVENTION OF NEW INFECTION.
        /// </summary>
        public static string CsPreventionOfNewInfection {
            get {
                return ResourceManager.GetString("CsPreventionOfNewInfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS &lt;u&gt;NO&lt;/u&gt; IMPROVEMENT!.
        /// </summary>
        public static string ImprovementNevagive {
            get {
                return ResourceManager.GetString("ImprovementNevagive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE &lt;u&gt;IS&lt;/u&gt; AN IMPROVEMENT!.
        /// </summary>
        public static string ImprovementPositive {
            get {
                return ResourceManager.GetString("ImprovementPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARE RESULTS.
        /// </summary>
        public static string MonitorCompareButton {
            get {
                return ResourceManager.GetString("MonitorCompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW ASSESSMENT.
        /// </summary>
        public static string MonitorReviewButton {
            get {
                return ResourceManager.GetString("MonitorReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COW STATUS INPUT.
        /// </summary>
        public static string MonitorStatusButton {
            get {
                return ResourceManager.GetString("MonitorStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY OF RESULTS.
        /// </summary>
        public static string MonitorSummaryButton {
            get {
                return ResourceManager.GetString("MonitorSummaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once SDCT has been implemented, continuous monitoring is required in order to refine practices on farm in order to optimise success levels and ultimately productivity, profitability and animal welfare..
        /// </summary>
        public static string MonitorText1 {
            get {
                return ResourceManager.GetString("MonitorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app will help you to analyse the infection rates of the herd at dry-off and calving. By inputing the infection status of each cow in the herd you can monitor the overall results and, together with SDCT assessment tool, analyse which areas are working well and where improvement may be required..
        /// </summary>
        public static string MonitorText2 {
            get {
                return ResourceManager.GetString("MonitorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcoming problems is part of everyday life when managing a dairy herd and SDCT is no different, by fostering good working relationships, MSD Animal Health Representatives, vets and farmers can work together to overcome any challenges which may arise..
        /// </summary>
        public static string MonitorText3 {
            get {
                return ResourceManager.GetString("MonitorText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCT provides both short term and long term benefits; fostering responsible usage of antibiotics in the food chain, improving productivity and reducing infection treatment costs are all strong reasons to implement and maintain SDCT..
        /// </summary>
        public static string MonitorText4 {
            get {
                return ResourceManager.GetString("MonitorText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT IS IMPORTANT TO CONTINUE MONITORING THE FARM ONCE SDCT IS IMPLEMENTED....
        /// </summary>
        public static string MonitorTitle1 {
            get {
                return ResourceManager.GetString("MonitorTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT YOU NEED TO MONITOR....
        /// </summary>
        public static string MonitorTitle2 {
            get {
                return ResourceManager.GetString("MonitorTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO DEAL WITH ANY PROBLEMS WHICH MAY ARISE....
        /// </summary>
        public static string MonitorTitle3 {
            get {
                return ResourceManager.GetString("MonitorTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE BENEFITS OF MAINTAINING SDCT....
        /// </summary>
        public static string MonitorTitle4 {
            get {
                return ResourceManager.GetString("MonitorTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comparison will be available once you have input more data..
        /// </summary>
        public static string NoResultsCompareCaption {
            get {
                return ResourceManager.GetString("NoResultsCompareCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTS COMPARISON.
        /// </summary>
        public static string NoResultsComparePageTitle {
            get {
                return ResourceManager.GetString("NoResultsComparePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORRY, WE DONT HAVE ENOUGH DATA TO COMPARE AT THIS TIME.
        /// </summary>
        public static string NoResultsCompareText {
            get {
                return ResourceManager.GetString("NoResultsCompareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSESSMENT.
        /// </summary>
        public static string RootAssessment1 {
            get {
                return ResourceManager.GetString("RootAssessment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRY COW TREATMENT.
        /// </summary>
        public static string RootAssessment2 {
            get {
                return ResourceManager.GetString("RootAssessment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTIVE.
        /// </summary>
        public static string RootAssessment3 {
            get {
                return ResourceManager.GetString("RootAssessment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONITOR.
        /// </summary>
        public static string RootMonitor1 {
            get {
                return ResourceManager.GetString("RootMonitor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS OF SELECTIVE.
        /// </summary>
        public static string RootMonitor2 {
            get {
                return ResourceManager.GetString("RootMonitor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRY COW TREATMENT.
        /// </summary>
        public static string RootMonitor3 {
            get {
                return ResourceManager.GetString("RootMonitor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY OF RESULTS.
        /// </summary>
        public static string SummaryResultTitle {
            get {
                return ResourceManager.GetString("SummaryResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string SurveyNoButton {
            get {
                return ResourceManager.GetString("SurveyNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARE PREVIOUS RESULTS.
        /// </summary>
        public static string SurveyResultCompareButton {
            get {
                return ResourceManager.GetString("SurveyResultCompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREAS FOR IMPROVEMENT.
        /// </summary>
        public static string SurveyResultImprovementTitle {
            get {
                return ResourceManager.GetString("SurveyResultImprovementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWITCHING TO SDCT &lt;u&gt;IS&lt;/u&gt; SUITABLE ON THIS FARM!.
        /// </summary>
        public static string SurveyResultSdctSuitable {
            get {
                return ResourceManager.GetString("SurveyResultSdctSuitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWITCHING TO SDCT MAY POSE A &lt;u&gt;RISK&lt;/u&gt; FOR UDDER HEALTH ON THIS FARM!.
        /// </summary>
        public static string SurveyResultSdctUnsuitable {
            get {
                return ResourceManager.GetString("SurveyResultSdctUnsuitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTS.
        /// </summary>
        public static string SurveyResultsPageTitle {
            get {
                return ResourceManager.GetString("SurveyResultsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Questions.
        /// </summary>
        public static string SurveyStartQuestionsButton {
            get {
                return ResourceManager.GetString("SurveyStartQuestionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string SurveyYesButton {
            get {
                return ResourceManager.GetString("SurveyYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is being provided strictly as a convenience to its users. Any and all liability arising directly or indirectly from the use of this tool is hereby disclaimed. The tool is provided without any warranty expressed or implied, including any implied warranties of merchantability, fitness for a particular purpose or non-infringement. Any and all indirect, special, incidental, consequential or punitive damage arising from any use of this tool or data generated with the tool is specifically disclaimed and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string TermsAcceptButton {
            get {
                return ResourceManager.GetString("TermsAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.merck.com/about/how-we-operate/privacy/internet-privacy-policy.html.
        /// </summary>
        public static string TermsUrl {
            get {
                return ResourceManager.GetString("TermsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTS COMPARISONS.
        /// </summary>
        public static string TitleResultComparison {
            get {
                return ResourceManager.GetString("TitleResultComparison", resourceCulture);
            }
        }
    }
}
